sudo: required

language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - redis-server



env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - sudo service redis-server stop
  - sleep 10
  - sudo cat /etc/redis/redis.conf
  - sudo sed -i 's|appendonly no|appendonly yes|g' /etc/redis/redis.conf
  - sudo sed -i "s|# requirepass foobared|requirepass ${DNB_ENV_APP_S2_DB_PASS}|g" /etc/redis/redis.conf
  - sudo cat /etc/redis/redis.conf
  - sudo ls -al  /var/lib/redis
  - sudo find /var/lib/redis -mindepth 1 -delete
  - sudo tar -xvf ~/data.tar -C /var/lib/redis --strip 1 
  - sudo chown redis:redis /var/lib/redis/appendonly.aof
  - sudo chmod 660 /var/lib/redis/appendonly.aof 
  - sudo ls -al  /var/lib/redis
  - sudo service redis-server start
  - sleep 10

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
